### ISSUE TITLE
YAML files are completely encrypted

### ISSUE THREAD

**Issue by rkokkelk** [inhumantsar/python-ansible-vault-rekey#358]
ansible-vault-rekey version: `2.0.0`
Python version: `3.8`
Operating System: `Ubuntu-20.04`

## Description

When running the ansible-vault-rekey it complete encrypts YAML files which only include ansible vault entries but are not an entire vault file.

```bash
ansible-vault-rekey -k
```

**Input file**

```yaml
- hosts: webservers
  name: update web servers
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache config file
    template:
      dest: /etc/httpd.conf
      src: /srv/httpd.j2
- hosts: databases
  name: update db servers
  remote_user: root
  tasks:
  - name: ensure postgresql is at the latest version
    yum:
      name: postgresql
      state: latest
  - name: ensure that postgresql is started
    service:
      name: postgresql
      new_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31616135356533306166313261326661656432613238643637613638633135323138313662333737
          3136303066393434313130386664613563616431323330620a313530306231313330656633356236
          30643337646337663162313463626331333232373135306538313466663136663066366632316637
          6636646437363061360a346362623764306531303766646266656237366535643262613838616261
          3066
      state: started
```
**Output file**
```
$ANSIBLE_VAULT;1.1;AES256
61346234663963663965326364656234623531343631303735313961653732646234616565343033
3765616662343030373638616233396238333336613331310a666339323864613566306133356265
65356566373465373633356430613732636338643234666238616636396564316139326335383938
3939353339363166630a613031633733613931313732333437613335363664616264343561613564
63356532653239623366666462623139613030316539626337366436323462646531303839326636
61323234306338303764306462633336383632666435353835363961313436393366343230623938
30393639383934373364303130303533336631636336333633386464393435336337313838623933
35353761346539396666313134323665626562636162313732353031366130626562373931646436
30373362376565326662376335356662346236336665393337343434376333346266376262636436
64366361373837616537313136333962313862346265323563636631633131356562613134313830
30663331323932663931333963373536336139613763613536373662626234633365616235353436
31383963313064663638643430313535663038323062383339393235383932393862333266643536
63303230306230323566303162653037373230623739656237396231663831623466393639333832
37366561613165396434353836353163316363623739666365333165386439343765363532383230
31366265343730333665366362643561663035313139616563306337363033363637303535636134
36356264336535393831656565393036313361313333363463336234636261323261656131633034
36306433636664666533383537633337363436623432616632353665356462363037396634656230
30613936393834396232363564333262626163333635396161363031303336656465663637313264
64666433373464353838353564636165343164353430333062313262636632353665316635376331
31613432656534613139386265376664656139306534373738643565333464396231343235333763
64353336633531346635366633323138653465363536633434343565633131613638396630643832
39666436653266303833623964393433613730306266616534363262316438633036383137373831
63663261633235386132663863343862363461616433663638633162613838396233353035643762
32353733346133363034616631663230343837366636383939393334323539376466386632313332
38373561626633353835646634386563656436366430346536396636346664353130343039363434
63393534303133343065366234336565623435353232663064323432656431613066333433333466
33613365316663373730303761623434663934633330613865636132653335306332353764616438
63376465643939373137306166373161623861613161396239656631353265663231303935663437
34613732333563373765666363373639366263623636646562383966303661373338626630666164
61636536663537313036316332323365643034356434393535323532613765373333343030643833
33303462616236303034663234383436636264386662643062373765336264646238636634303361
38323864376130626634636538623162366534363537663131376537616162383866396635393562
61633930393536633565386332633064333936663962303436356462383639396562
```
